on:
  push:
    branches: [ develop ]

name: Deploy "DASHBOARD PHARMACY ALTEACARE" to Development Environment on Vercel

jobs:
  deploy:
    name: Deploy "DASHBOARD PHARMACY ALTEACARE" to Development Environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create .env
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_PORT: 8888
          envkey_REACT_APP_MOENGAGE: ${{ secrets.TOKEN_MOENGAGE_DEVELOPMENT }}
          envkey_REACT_APP_API_BASE_URL: https://dev-services.alteacare.com/
          envkey_REACT_APP_API_USER_URL: user
          envkey_REACT_APP_API_ECOMMERCE_URL: ecommerce
          envkey_REACT_APP_API_ECOMMERCE_DASHBOARD_SERVICE_URL: ecommerce-dashboard
          envkey_REACT_APP_API_FILE_URL: file
          envkey_REACT_APP_API_DATA_URL: data
          envkey_REACT_APP_SLACK_WEBHOOK: https://hooks.slack.com/services/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
          envkey_REACT_APP_ENV: development

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          alias-domains: dev-dashboard-pharmacy.alteacare.com
          working-directory: ./
          scope: ${{ secrets.TEAM_ID }}
          github-comment: false

      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: 'deployment-information'
          SLACK_COLOR: ${{ job.status }}
          SLACK_USERNAME: 'AlteaCare Bot'
          SLACK_ICON: 'https://alteacare-assets.s3.ap-southeast-1.amazonaws.com/images/logo_48x48.png'
          SLACK_FOOTER: 'AlteaCare Deployment Information'
